version: "3.8"
services:
  nodeserver:
    build:
      context: ./app
    container_name: app
    ports:
      - "3000:3000"
    entrypoint: wait-for db:3306 -t 40 -- npm start
    volumes:
      - ./app/src:/usr/src/app/src
    networks:
      - app-network
    depends_on:
      - db
  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - app-network
  db:
    image: mysql:latest
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
